BUG:
  Think I've finally tracked down the Database connection problems.  Quoted from an email:

Jim,

  I put guards in on all the non-servlet "project.getConnection()" calls to call project.closeConnection()".  Here is what I found, if the connection is already closed (for some reason), you get this error and stack trace. I think we saw this last week.

[SimpleThreadPoolWorker-2] ERROR dart.server.task.ScheduledTask  - Execution failed: TestProject:dart.server.task.QueueManager:0
java.sql.SQLException: Already closed.
	at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:77)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:180)
	at dart.server.Database.closeConnection(Database.java:216)
	at dart.server.Container.closeConnection(Container.java:158)

But the connection pool doesn't mark the connection as idle/returned.  This status shows the disconnect:  The "Got connection" is my internal bookkeeping.

Database: 2 active 2 idle Dart's Count: 2
Got connection: org.apache.commons.dbcp.PoolableConnection@137fce3
        dart.server.task.QueueManager.execute(QueueManager.java:26)
        dart.server.task.ScheduledTask.execute(ScheduledTask.java:36)
        org.quartz.core.JobRunShell.run(JobRunShell.java:203)

Because I remove the connection from my internal list of open connections before I decrement "Dart's Count", the list forgets about the connection, but Dart and the ConnectionPool don't.  So I added this code in Database.java:

      try {
        c.close();
      } catch ( SQLException sqle ) {
        // got a problem, mark this guy as invalid and re-throw
        logger.error ( project.getTitle() + ": Something was wrong with this connection, marking it invalid.", sqle );
        connectionPool.invalidateObject ( c );
        throw sqle;
      }




git-svn-id: http://svn.na-mic.org/Dart/trunk@382 b2c14c61-d7ef-0310-8715-841e9ab387fe